name: beautifulDefinedKeyspaceName
replicationFactor: 1
strategy: org.apache.cassandra.locator.SimpleStrategy
columnFamilies:
- name: columnFamily1
  type: STANDARD
  keyType: UTF8Type
  comparatorType: UTF8Type
  defaultColumnValueType: UTF8Type
  rows:
  - key: key01
    columns:
    - {name: columnName1, value: columnValue1}
- name: columnFamily2
  type: SUPER
  keyType: UTF8Type
  comparatorType: UTF8Type
  subComparatorType: UTF8Type
  defaultColumnValueType: UTF8Type
  rows:
  - key: key02
    superColumns:
    - name: superColumnName2
      columns:
      - {name: columnName2, value: long(2)}
- name: standardCounterColumnFamily
  keyType: UTF8Type
  comparatorType: UTF8Type
  defaultColumnValueType: CounterColumnType
  rows:
  - key: key10
    columns:
    - {name: columnName11, value: 11}
- name: superCounterColumnFamily
  type: SUPER
  keyType: UTF8Type
  comparatorType: UTF8Type
  subComparatorType: UTF8Type
  defaultColumnValueType: CounterColumnType
  rows:
  - key: key10
    superColumns:
    - name: superColumnName11
      columns:
      - {name: columnName111, value: 111}